### ISSUE TITLE
NTM crash by start

### ISSUE THREAD

**Issue by Gaprosys** [BarelyAlive/Nether-Tweaks#2]
---- Minecraft Crash Report ----
// My bad.

Time: 21.10.16 20:09
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:32)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:43)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:611)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:231)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:32)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:43)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:611)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:231)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3546419872 bytes (3382 MB) / 4698144768 bytes (4480 MB) up to 4698144768 bytes (4480 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:-UseAdaptiveSizePolicy -Xmn5G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	U	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	U	Chaust{0.0.4} [Chaust] (Chaust-0.0.4.jar) 
	U	NTMCompatibility{null} [NTMCompatibility] (NetherTweaksMod-1.6.0.jar) 
	U	SFHCore{1.0.1} [SFHCore] (SFHCore-1.0.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GTX 980/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.2.2099
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by BarelyAlive** [comment]
Fixed
